Version comparison
UST-QuAntiL/qc-atlas-ui pull request #166
Opened 2021-08-29 10:33 UTC by emymaria

Compare two different versions of algorithm

https://user-images.githubusercontent.com/68675647/131247315-f252612b-9204-4425-b1f1-dcaa4120c555.mp4

2021-08-30 07:35 UTC, salmma commented
solves #149

2021-08-30 09:04 UTC, lharzenetter requested changes

2021-08-30 09:04 UTC, lharzenetter commented on src/app/components/algorithms/dialogs/compare-version-dialog.component.ts
> +  comparisons: ComparedData[];
I guess `differences` is the better choice of words.

2021-09-02 12:03 UTC, salmma requested changes
See my comments.
Please also do the same procedure for implementations, as there are also revisions available :)

2021-09-06 06:27 UTC, lharzenetter approved these changes

2021-09-06 07:39 UTC, salmma requested changes
As already mentioned, please also implement the revision comparison for implementations

2021-09-13 16:12 UTC, salmma requested changes
* The "Compare Versions" button should be removed at other tabs than the "General" tab, as no comparison is made, e.g., between previous related algorithms and the latest list - so this could confuse the user.
* same for Implementation
<img width="544" alt="Bildschirmfoto 2021-09-13 um 18 07 45" src="https://user-images.githubusercontent.com/23473511/133118778-66984489-3192-47cf-aeba-cf4898661aac.png">

* the "Compare Versions" buttons differ between Algorithm and Implementation view

2021-09-15 09:15 UTC, salmma approved these changes

2021-09-15 09:15 UTC, merged