Hide editing feature #161
UST-QuAntiL/qc-atlas-ui pull request #167
Opened 2021-09-12 05:39 UTC by emymaria

Disabling editing when enable editing is unchecked in settings

2021-09-13 14:30 UTC, lharzenetter commented on src/app/components/generics/link-input/link-input.component.ts
> +  readonly UiFeatures = UiFeatures;
I guess you don't need this here.

2021-09-13 14:30 UTC, lharzenetter commented on src/app/components/generics/property-input/checkbox-input.component.ts
> +  readonly UiFeatures = UiFeatures;
I guess you don't need this here.

2021-09-13 14:30 UTC, lharzenetter commented on src/app/components/generics/property-input/text-input.component.ts
> +  readonly UiFeatures = UiFeatures;
I guess you don't need this here.

2021-09-15 08:30 UTC, salmma requested changes
As discussed, please 
* hide the "add item" and "delete item" buttons in all lists
* hide the Actions column in all lists
* hide the edit and delete buttons, e.g., for given "Required compute resource properties" in the "General" tab of an algorithm/implementation/compute resource.
* hide the add button for "Required compute resource properties"
* hide the delete button for given Problem types in the "General" tab of an algorithm
* hide the delete button for given Application areas in the "General" tab of an algorithm

2021-09-30 09:27 UTC, salmma approved these changes
LGTM

2021-09-30 09:33 UTC, lharzenetter approved these changes

2021-09-30 09:33 UTC, merged