Extending the columns similar to nisq analyser
UST-QuAntiL/qc-atlas-ui pull request #203
Opened 2022-03-14 10:59 UTC by emymaria

Adding the columns to execution tab of implementation

2022-03-15 09:51 UTC, salmma requested changes
small comment

2022-03-15 09:51 UTC, salmma commented on src/app/components/algorithms/implementation-view/implementation-execution/implementation-execution.component.ts
> +  QpuSelectionResultDto,
please, remove unused imports

2022-04-07 15:50 UTC, salmma requested changes
implementation-execution part LG
automatic refresh-branch can be deleted?
nisq-analyzer part: execute button does not work.

2022-04-10 11:41 UTC, emymaria commented
> implementation-execution part LG automatic refresh-branch can be deleted? nisq-analyzer part: execute button does not work.

compiler-comparision-automated-refresh can be removed

2022-04-13 12:55 UTC, salmma approved these changes
LG
Sorting for NISQ Analyzer in context of an algorithm (multiple tables) should be fixed
Checking if QPU data is up-to-date should be fixed.

2022-04-13 12:56 UTC, merged