Setting some columns fixed while scrolling in nisq analyser
UST-QuAntiL/qc-atlas-ui pull request #211
Opened 2022-05-01 09:37 UTC by emymaria

Fix the columns till sdk/compiler for nisq analyser tables of algorithm and implementation.

2022-05-02 08:03 UTC, salmma requested changes
Under Algorithm > NISQ Analyzer it should be avoided that long backend names (e.g., ibmq_qasm_simulator) is shortened, wenn scrolling, see video.
Is it also possible that under the column names of the sticky columns a line is presented (so directly under Provider, Backend, ... as separator, as for the other "normal" columns)

https://user-images.githubusercontent.com/23473511/166203352-f5f33cb3-3bd0-4268-9301-b0073cdab3cf.mov

2022-05-10 07:22 UTC, salmma requested changes
* Algo > Impl > Execution: QPU data should only be checked when the table is non-empty otherwise the check is shown forever:
<img width="741" alt="Bildschirmfoto 2022-05-10 um 09 17 14" src="https://user-images.githubusercontent.com/23473511/167571513-b103e48a-fb97-490f-a840-8df4ea913425.png">


* In all results table (execution, QPU-Analysis, Algo NISQ Analyzer) the sticky columns still have no border under the head:
<img width="287" alt="Bildschirmfoto 2022-05-10 um 09 20 00" src="https://user-images.githubusercontent.com/23473511/167571888-626b8247-8a31-4a08-8f36-64ab82a91677.png">

* see comment about any

2022-05-10 07:22 UTC, salmma commented on src/app/components/algorithms/implementation-view/implementation-execution/implementation-execution.component.ts
> +  @ViewChild(MatTable) table: MatTable<any>;
is it possible to define a specific type instead of any?

2022-05-12 14:31 UTC, emymaria commented
> 

<img width="683" alt="image" src="https://user-images.githubusercontent.com/68675647/168099148-59a9cc05-40b7-4de9-9a9c-6f28cf8254db.png">
<img width="716" alt="image" src="https://user-images.githubusercontent.com/68675647/168099306-3912e6b8-a4fc-47a5-abad-56cc50c94f6f.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/68675647/168099448-7841b336-e4de-44f9-8297-d895417e15a1.png">

I have the line under all headers. I checked in chrome and edge.

2022-05-12 14:34 UTC, salmma commented
I test with Firefox

2022-05-12 17:12 UTC, salmma approved these changes
LGTM

2022-05-12 17:13 UTC, merged